# Generated by Django 5.2.12 on 2026-03-31 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0002_feature_created_at_feature_created_by_feature_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='visibility',
            field=models.CharField(choices=[('only-me', 'Only Me'), ('public', 'Public')], default='only-me', max_length=10),
        ),
        migrations.AlterField(
            model_name='feature',
            name='notes',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
